spring.application.name=ms-aerotrans-catalogs
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aerotrans}
spring.datasource.username=${DB_USERNAME:aerotrans}
spring.datasource.password=${DB_PASSWORD:aerotrans}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
